# Change these first
owner: serie-a-logistics-solutions # Your GitHub organization or username, where this repository lives
repo: nx3_demo_status # The name of this repository

sites:
  - name: Node 1 - IAM Service
    url: https://transport-demo.on.nx3.cloud/monitoring/node1/auth/auth/health/live
    __dangerous__body_down_if_text_missing: '"status": "UP"'
  - name: Node 2 - IAM Service
    url: https://transport-demo.on.nx3.cloud/monitoring/node2/auth/auth/health/live
    __dangerous__body_down_if_text_missing: '"status": "UP"'
  - name: Node 1 - Backoffice Service
    url: https://transport-demo.on.nx3.cloud/monitoring/node1/rs/actuator/health
    __dangerous__body_down_if_text_missing: '"status" : "UP",'
  - name: Node 2 - Backoffice Service
    url: https://transport-demo.on.nx3.cloud/monitoring/node2/rs/actuator/health
    __dangerous__body_down_if_text_missing: '"status" : "UP",'
  - name: Database Service
    url: https://transport-demo.on.nx3.cloud/monitoring/node1/rs/actuator/health
    __dangerous__body_down_if_text_missing: '"validationQuery" : "isValid()"'
  - name: Monitoring
    url: https://transport-demo.kb.eu-west-1.aws.found.io/login?next=%2Fapp%2Fhome#/ 
  - name: EU-Licence-Classification Service
    url: https://eulicence-classification.nx3-services.cloud/api/health_check
 

status-website:
  baseUrl: /nx3_demo_status # where "repo" is your repository name
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: 	https://transport.test.nx3.io/assets/light_nx3.svg
  faviconSvg: https://transport.test.nx3.io/assets/light_nx3.svg
  name: System Status
  introTitle: ""
  introMessage: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
