# Change these first
owner: serie-a-logistics-solutions # Your GitHub organization or username, where this repository lives
repo: nx3_demo_status # The name of this repository

sites:
  - name: Demo Test
    url: https://transport.test.nx3.io/rs
  - name: Demo Integration
    url: https://transport-integration.nx3.io/rs
  - name: Demo AWS
    url: https://transport-demo.on.nx3.cloud/

status-website:
  baseUrl: /nx3_demo_status # where "repo" is your repository name
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: 	https://transport.test.nx3.io/assets/light_nx3.svg
  faviconSvg: https://transport.test.nx3.io/assets/light_nx3.svg
  name: Service Status
  introTitle: ""
  introMessage: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
